"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;function _toConsumableArray(a){return _arrayWithoutHoles(a)||_iterableToArray(a)||_nonIterableSpread()}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance")}function _iterableToArray(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}function _arrayWithoutHoles(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}}function asyncGeneratorStep(a,b,c,d,e,f,g){try{var h=a[f](g),i=h.value}catch(a){return void c(a)}h.done?b(i):Promise.resolve(i).then(d,e)}function _asyncToGenerator(a){return function(){var b=this,c=arguments;return new Promise(function(d,e){function f(a){asyncGeneratorStep(h,d,e,f,g,"next",a)}function g(a){asyncGeneratorStep(h,d,e,f,g,"throw",a)}var h=a.apply(b,c);f(void 0)})}}function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function")}function _defineProperties(a,b){for(var c,d=0;d<b.length;d++)c=b[d],c.enumerable=c.enumerable||!1,c.configurable=!0,"value"in c&&(c.writable=!0),Object.defineProperty(a,c.key,c)}function _createClass(a,b,c){return b&&_defineProperties(a.prototype,b),c&&_defineProperties(a,c),a}/**
 * 作者：罗学 
 * */var CanvasRun=/*#__PURE__*/function(){function a(){var b=this;_classCallCheck(this,a),this.timer=0,this.speed={x:0,y:0},this.VDomTree=[],this.moveDistance=0,this.classList={},this.gain=1,this.particleStore={},this.particlePics=[],this.envents={click:[],touchmove:[],touchstart:[],touchend:[],translateTop:[],translateleft:[],slowDown:[]},this.SimpleInterest=!0,this.paramsTranslateUnit=function(a){return parseInt(750*a/b.gain/document.body.clientWidth+"")},console.log("\u6CE8\u518C\u6210\u529F")}return _createClass(a,[{key:"init",// 初始化
value:function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b){var c,d,e,f,g,h,i,j,k,l,m,n,o=this;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return c=b.canvas,d=b.ctx,e=b.config,f=b.gain,g=void 0===f?1:f,h=b.noNeedOff,i=void 0!==h&&h,j=b.mounted,k=void 0===j?function(){}:j,l=b.created,m=void 0===l?function(){}:l,n=0,this.canvas=c,this.ctx=d,this.gain=g,m&&"function"==typeof m&&m(),a.next=8,this.compile(e);case 8:this.draw(),k&&"function"==typeof k&&k(),this.SimpleInterest&&(this.SimpleInterest=!1,this.touchstart(function(a){o.startClientX=a.changedTouches[0].clientX,o.startClientY=a.changedTouches[0].clientY,o.endClientX=0,o.endClientY=0,o.moveClientX=0,o.moveClientY=0,o.moveDistance=0,o.dispatchTouchstart(a)}),this.touchend(function(a){o.endClientX=a.changedTouches[0].clientX,o.endClientY=a.changedTouches[0].clientY,o.moveClientX=0,o.moveClientY=0;var b=o.endTime-o.startTime,c=o.endClientX-o.startClientX,d=o.endClientY-o.startClientY;30<b&&150>b&&10>Math.abs(c)&&10>Math.abs(d)&&o.dispatchClick(a),o.speed={x:parseInt(1e3*(c/b)+""),y:parseInt(1e3*(d/b)+"")},o.dispatchEnd(a)}),this.touchmove(function(a){o.moveClientX=a.changedTouches[0].clientX,o.moveClientY=a.changedTouches[0].clientY,o.dispatchMove(a),o.moveSlide(n-a.changedTouches[0].clientX),o.draw(),n=a.changedTouches[0].clientX}));;case 12:case"end":return a.stop();}},a,this)}));return function init(){return a.apply(this,arguments)}}()},{key:"destroyed",value:function destroyed(){this.clear(),this.VDomTree=[{}]}},{key:"$apply",// 更新画布
value:function $apply(){this.init({canvas:this.canvas,ctx:this.ctx,config:this.VDomTree})}},{key:"compile",// 编译步骤 
value:function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b){var c,d,e,f,g,h,j,k,l=this;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return this.classList={},c=function(){},d=["click","touchmove","touchstart","touchend"],e=["w","fontSize","color","opcity"],f=["w","h"],g=function(a,b){e.forEach(function(c){!a[c]&&b&&b[c]&&(a[c]=b[c])})},h=function(a){a&&f.forEach(function(b){"nowrap"===a.whiteSpace&&(a[b]=l.computedWidth(a)[b]||a[b])})},j=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(){var f,m,n,o,e=arguments;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:f=0<e.length&&void 0!==e[0]?e[0]:b,m=1<e.length&&void 0!==e[1]?e[1]:null,m&&(m.childX=0),n=/*#__PURE__*/regeneratorRuntime.mark(function(a){return regeneratorRuntime.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:if(f[a].class&&l.analysisString(f[a].class).forEach(function(b){return k(b,f[a])}),b.t0=f[a].children&&0<f[a].children.length,!b.t0){b.next=5;break}return b.next=5,j(f[a].children,f[a]);case 5:if(f[a].parent=m,f[a].index=a,"string"!=typeof f[a].backgroundImage){b.next=11;break}return b.next=10,l.createdImg(f[a].backgroundImage);case 10:f[a].backgroundImage=b.sent;case 11:;// 继承关系
g(f[a],m),l.objectkeys(f[a]).forEach(function(b){if(!(-1<["zIndex","index","maxLine","scale","opcity","rotate"].indexOf(b))&&("number"==typeof f[a][b]&&(f[a][b]*=l.gain),l.isPlainObject(f[a][b])&&"parent"!==b)){var c=l.objectkeys(f[a][b]);c.forEach(function(c){f[a][b][c]*=l.gain})}}),d.forEach(function(b){f[a][b]||(f[a][b]=c)});case 15:case"end":return b.stop();}},n)}),o=0;case 5:if(!(o<f.length)){a.next=10;break}return a.delegateYield(n(o),"t0",7);case 7:o++,a.next=5;break;case 10:;h(m);case 12:case"end":return a.stop();}},a)}));return function(){return a.apply(this,arguments)}}(),k=function(a,b){l.classList[a]?l.classList[a].push(b):l.classList[a]=[b]},a.next=11,j();case 11:return this.VDomTree=b,a.abrupt("return",!0);case 13:case"end":return a.stop();}},a,this)}));return function compile(){return a.apply(this,arguments)}}()},{key:"moveSlide",// 滑动监听，计算并设置移动距离
value:function moveSlide(a){30>Math.abs(a)&&(this.moveDistance=a)}},{key:"dispatchMove",value:function dispatchMove(){var a=this.envents.touchmove,b=this.moveClientX,c=this.moveClientY;this.dispatchEvent(a,b,c,"touchmove")}},{key:"dispatchClick",// 事件派发 click
value:function dispatchClick(){var a=this,b=this.envents.click,c=this.endClientX,d=this.endClientY;setTimeout(function(){a.dispatchEvent(b,c,d,"click")},300)}},{key:"dispatchTouchstart",// 事件派发 click
value:function dispatchTouchstart(){var a=this.envents.touchstart,b=this.startClientX,c=this.startClientY;this.dispatchEvent(a,b,c,"touchstart")}},{key:"dispatchEvent",value:function dispatchEvent(a,b,c){for(var d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:"click",e=0;e<a.length;e++)if(b>=a[e].area.l&&b<=a[e].area.r&&c>=a[e].area.t&&c<=a[e].area.b)// 只允许同时触发一个事件，阻止向下传递
return a[e]&&"function"==typeof a[e][d]&&a[e][d].bind(this)(a[e]),void this.draw()}},{key:"dispatchEnd",value:function dispatchEnd(){var a=this.envents.touchend,b=this.endClientX,c=this.endClientY;this.dispatchEvent(a,b,c,"touchend")}},{key:"clear",// 清理上次绘画
value:function clear(){this.envents={click:[],touchmove:[],touchstart:[],touchend:[],translateTop:[],translateleft:[],slowDown:[]}}},{key:"offCanvas",// 
value:function offCanvas(){for(var a=this,b=this.getFile,c=[],d=0;d<b.length;d++)b[d].particle&&c.push(b[d]);c.map(function(b){a.ctx.save(),a.drwaView(b),a.ctx.restore();var c=b.x,d=b.y,e=b.w,f=b.h,g=b.particle,h=g.size||5,i=g.d||0,j=function(){return .5*i*(.5<Math.random()?Math.random():-Math.random())},k=[];(function store(){for(var g=c;g<=c+e;g+=h)for(var i=d;i<=d+f;i+=h)k.push({file:a.ctx.getImageData(g,i,h,h),x:g,y:i,w:h,h:h});a.particleStore[b.class]=k})();var l=[];a.ctx.save(),a.drwaView(b),a.ctx.restore();var m=a.ctx.getImageData(0,0,500,500);l.push(m),a.particlePics[b.class]=l,console.log(m)}),console.log("============================",c,"============================")}},{key:"draw",// 绘图
value:function(){var a=this;this.clear();var b=this.getFile,c=0,d=function(){var e=Object.assign({},b[c],{self:b[c]});a.warp(e),c++,b.length===c||d()};d()}},{key:"eventStoreArea",// 事件储存，把层级高的事件放在上面
value:function eventStoreArea(a,b){this.envents[a]&&this.envents[a].unshift(b)}},{key:"rpxToFix",// 把px转化成适合屏幕大小尺寸
value:function rpxToFix(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"10rpx";return a+="",/^[\d]+(rpx)$/.test(a)?this.trasnslateUnit(parseInt(a))*this.gain:a}},{key:"errorLog",value:function errorLog(a){return console.error(a),!0}},{key:"drwaRoundRect",// 画圆角矩形
value:function drwaRoundRect(a){var b=a.x,c=void 0===b?0:b,d=a.y,e=void 0===d?0:d,f=a.w,g=void 0===f?0:f,i=a.h,j=void 0===i?0:i,h=a.borderRadius,k=void 0===h?0:h,l=a.border,m=void 0===l?"1rpx solid transparent":l;m=m||"1rpx solid transparent";var n=this.analysisString(m);if(3>n.length)return this.errorLog("\u60A8\u8BBE\u7F6E\u7684border\u7F3A\u5C11\u53C2\u6570");var o=this.rpxToFix(n[0]),p=this.rpxToFix(n[2]),q=this.analysisString(n[1],":"),s=k;return g<2*s&&(s=g/2),j<2*s&&(s=j/2),this.ctx.strokeStyle=p,"dashed"===q[0]&&this.ctx.setLineDash([q[1]||10,q[2]||3]),this.ctx.lineWidth=o,this.ctx.beginPath(),this.ctx.moveTo(c+s,e),this.ctx.arcTo(c+g,e,c+g,e+j,s),this.ctx.arcTo(c+g,e+j,c,e+j,s),this.ctx.arcTo(c,e+j,c,e,s),this.ctx.arcTo(c,e,c+g,e,s),this.ctx.closePath(),this.ctx}},{key:"drawFont",value:function drawFont(a){var b=this,c=a.fontSize,d=a.color,e=void 0===d?"#000000":d,f=a.lineHeight,g=a.maxLine,i=a.text,j=a.textAlign,k=void 0===j?"start":j,l=a.overText,m=a.overTextColor,n=a.fontWeight,o=a.x,p=a.y,q=a.w,r=a.h;this.ctx.save(),f=f||c,this.ctx.font="".concat(n?n+" ":"").concat(c,"px Arial"),"center"===k&&(o+=q/2),"end"===k&&(o+=q),this.ctx.textAlign=k;var h=this.computedText(i,c,q);return h.forEach(function(a,d){(i=a.resText,!(d>=g))&&(d===g-1&&Math.abs(q-a.tw)<c&&(l?(i=i.substr(0,i.length-(1+l.length))+"...",b.ctx.fillStyle=m||e,b.ctx.fillText(l,o+b.ctx.measureText(i).width,p+f)):i=i.substr(0,i.length-1)+"..."),p+=f,b.ctx.fillStyle=e,b.ctx.fillText(i,o,p))}),this.ctx.restore(),this.ctx}},{key:"getParticle",// 粒子化
value:function getParticle(a){var b=this;this.drwaView(a);var c=[],d=a.x,e=a.y,f=a.w,g=a.h,h=a.particle,k=h.size||5,l=h.d||0,m=function(){return .5*l*(.5<Math.random()?Math.random():-Math.random())};this.particleStore[a.class]?function put(){for(var c=b.particleStore[a.class],d=0;d<c.length;d++)c[d]&&c[d].file&&b.ctx.putImageData(c[d].file,c[d].x+m(),c[d].y+m())}():function store(){for(var h=d;h<=d+f;h+=k)for(var i=e;i<=e+g;i+=k)c.push({file:b.ctx.getImageData(h,i,k,k),x:h,y:i,w:k,h:k});b.particleStore[a.class]=c,b.getClassList[a.class][0].opcity=0}()}},{key:"drwaView",value:function drwaView(a){var b=a.backgroundImage,c=a.backgroundColor,d=void 0===c?"transparent":c,e=a.x,f=a.y,g=a.w,i=a.h,j=a.text,k=a.backgroundSize,l=a.backgroundPosition,m=a.scale,n=a.opcity,o=a.rotate;0<=n&&(this.ctx.globalAlpha=n),m&&(this.ctx.translate(e+g/2,f+i/2),this.ctx.scale(m.x,m.y),this.ctx.translate(-(e+g/2),-(f+i/2))),o&&(this.ctx.translate(e+g/2,f+i/2),this.ctx.rotate(parseInt(o)*Math.PI/180),this.ctx.translate(-(e+g/2),-(f+i/2))),this.drwaRoundRect(a).stroke(),this.ctx.clip(),this.ctx.fillStyle=d,this.ctx.fillRect(e,f,g,i),l&&(e+=l.x,f+=l.y),k&&(g=k.w,i=k.h),this.ctx&&b&&this.ctx.drawImage(b,e,f,g,i),this.ctx&&j&&this.drawFont(a)}// 视图包裹器
},{key:"viewWrap",value:function viewWrap(a){this.ctx.save(),a.particle?this.getParticle(a):this.drwaView(a),this.ctx.restore()}},{key:"eventWrap",// 事件包裹器
value:function eventWrap(a){var b=this,c=a.self,d=a.x,f=a.y,g=a.w,i=a.h,e=a.click,j=a.touchstart,k=a.touchmove,l=a.touchend;d/=this.gain,f/=this.gain,g/=this.gain,i/=this.gain,[e,j,k,l].forEach(function(a){if(!(a&&"defaultEvent"===a.name)&&a&&"function"==typeof a){var e={area:{t:f,b:f+i,l:d,r:d+g},self:c};e[a.name]=a,b.eventStoreArea(a.name,e)}})}},{key:"warp",// 将事件跟绘图区分开，分别处理
value:function warp(a){var b=this.canvas.width,c=this.canvas.height;0>a.x+b||0>a.y+c||a.x>b||a.y>c||(this.viewWrap(a),this.eventWrap(a))}},{key:"computedWidth",// 计算父级宽度
value:function computedWidth(a){function b(a){return a?a:0}if(!a.children)return{w:0,h:0};var c=0,d=0;// w = (parent.children.length - 1) * 168;
return c+=b(a.paddingLeft)+b(a.paddingRight),a.children.forEach(function(a){d=a.h>d?a.h:d,c+=b(a.w)+b(a.maginLeft)+b(a.marginRight)}),c-=800/a.children.length,{w:c,h:d}}},{key:"slideSide",// 滑动边界
value:function slideSide(a,b,c,d){b[a]>c?(b[a]=c,cancelAnimationFrame(this.timer)):b[a]<d&&(b[a]=d,cancelAnimationFrame(this.timer))}},{key:"canLRSlide",// 能够左右滑动
value:function canLRSlide(a){function b(a){return a?a:0}var c=this,d=a.x||0,e=a.y||0,f=a.computedW||0,g=a.computedH||0,i=a.children[0]?a.children[0].maginLeft||0:0,j=document.body.clientWidth-a.w/this.gain;a.computedW=a.w/this.gain,a.computedH=a.h/this.gain,d/=this.gain,e/=this.gain,f/=this.gain,g/=this.gain;var k={t:e,b:e+g,l:d,r:d+f};this.eventStoreArea("touchmove",{area:k,touchmove:function touchmove(){c.clear(),cancelAnimationFrame(c.timer),a.marginLeft=-1*c.moveDistance+b(a.marginLeft)}}),this.eventStoreArea("touchend",{area:k,touchend:function touchend(){c.clear(),clearInterval(c.timer);var d=c.speed.x*c.gain;if(!(300>Math.abs(d))){var e=function(){0<d?d-=10*c.gain:d+=10*c.gain,a.marginLeft=1*d/100+b(a.marginLeft),c.draw(),Math.abs(d)<=10*c.gain||(c.timer=requestAnimationFrame(e))};e()}}}),this.slideSide("marginLeft",a,i,j)}},{key:"slideTop",value:function slideTop(a,b){this.translateSlide(a,b)}},{key:"translateSlide",value:function translateSlide(a,b){var c=this,d=0,e=a.slideSpeed||3,f=0>a.slideTop;if(!(b.slideRunning&&Math.abs(a.slideTop)>e)){b.slideRunning=!0;var g=function(){return(a.slideTop=f?a.slideTop+e:a.slideTop-e,b.marginTop||(b.marginTop=0),b.marginTop=f?b.marginTop+e:b.marginTop-e,c.draw(),Math.abs(a.slideTop)<=e)?(b.slideRunning=!1,void window.cancelAnimationFrame(d)):void(d=window.requestAnimationFrame(g))};d=window.requestAnimationFrame(g)}}},{key:"modify",// 修饰动作
value:function modify(a,b){function c(a){return a?a:0}return b?(a.canLRSlide&&this.canLRSlide(b),a.slideTop&&this.slideTop(a,b),a.position)?(a.x=a.position.x,a.y=a.position.y,a):(a.x=c(b.x)+c(b.paddingLeft)+c(a.marginLeft),a.y=c(b.y)+c(b.paddingTop)+c(a.marginTop),"nowrap"===b.whiteSpace)?(a.x=c(b.childX)+c(b.paddingLeft)+c(a.marginLeft)+c(b.marginLeft),b.childX=c(b.childX)+a.w+c(a.marginLeft),a):a:a}},{key:"touchstart",// 封装 touchstart 事件
value:function touchstart(a){var b=this;this.canvas.addEventListener("touchstart",function(c){b.startTime=Date.now(),a(c)})}},{key:"touchend",// 封装 touchend 事件
value:function touchend(a){var b=this;this.canvas.addEventListener("touchend",function(c){b.endTime=Date.now(),a(c)})}},{key:"touchmove",// 封装 touchmove事件
value:function touchmove(a){this.canvas.addEventListener("touchmove",function(b){a(b)})}},{key:"analysisString",// ============================工具方法===========================================
/**
   * 解析字符串 
   * '1rpx solid red' return ['1rpx','solid','red'];
   */value:function analysisString(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:" ",c=[];return a?(a.trim().split(b).forEach(function(a){c.push(a.trim())}),c):c}},{key:"computedText",value:function computedText(){for(var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:28,c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:200,d=a.split("\n"),e=[],f=function(a){var d=a.split(""),e=0,f=0,g=[],h="";return d.map(function(a){var d=/[\w|\d|,|.]/.test(a)?b/2:b;e>c-b&&(h="",e=0,f++),e+=d,h+=a,g[f]={resText:h,tw:e}}),g},g=0;g<d.length;g++)e.push.apply(e,_toConsumableArray(f(d[g])));return e}},{key:"createdImg",// 见图片转为canvas可用的img对象
value:function createdImg(a){return new Promise(function(b,c){var d=new Image;// 解决跨域问题
d.crossOrigin="anonymous",d.onload=function(){b(d)},d.onerror=function(a){c(a)},d.src=a})}},{key:"trasnslateUnit",// 把数据转化呈用户适配用户屏幕  
value:function trasnslateUnit(a){return parseInt(a*document.body.clientWidth/750+"")}},{key:"sort",// 排序
value:function sort(a){return a.sort(function(c,d){return c=c.zIndex||0,d=d.zIndex||0,c>d?1:c<d?-1:0})}},{key:"downloadFile",// 下载资源，并返回进度
value:function downloadFile(a,b){try{(function(){for(var c=0,d=function(d){a[d].then(function(e){a[d]=e,c++,b(a,c/a.length)})},e=0;e<a.length;e++)d(e)})()}catch(a){}}},{key:"isPlainObject",value:function isPlainObject(a){var b=Object.prototype.toString;return"[object Object]"===b.call(a)}},{key:"objectkeys",value:function objectkeys(a){return this.isPlainObject(a)?Object.keys(a):[]}},{key:"getClassList",get:function get(){return this.classList}},{key:"getFile",// 递归遍历得到所有dom， 并排序文件，后续可能会增加功能
get:function get(){var a=this,b=[];if(this.VDomTree&&0<this.VDomTree.length){var c=function(){var d=0<arguments.length&&void 0!==arguments[0]?arguments[0]:a.VDomTree,e=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null;e&&(e.childX=0);for(var f=0;f<d.length;f++)0>d[f].zIndex||"none"===d[f].display||(b.push(a.modify(d[f],e)),d[f].children&&0<d[f].children.length&&c(d[f].children,d[f]))};c()}return this.sort(b)}},{key:"createdImageUrl",// 生成图片,此方法需要在所有canvas绘制完成后调用
get:function get(){return this.canvas.toDataURL("image/png")}}]),a}();exports.default=CanvasRun;